### ISSUE TITLE
Cannot load model without pytorch-lightning (No module named 'pytorch_lightning')

### ISSUE THREAD

**Issue by wdeback** [ozanciga/self-supervised-histopathology#1]
Hi Ozan,

We've been reading your paper (https://arxiv.org/abs/2011.13971) with a lot of interest. Very nice work!

Now, we'd like to try out your [trained model](https://github.com/ozanciga/self-supervised-histopathology/releases/download/1/_ckpt_epoch_9.ckpt), using the code you provide in the README. However, we are having some difficulties. Specifically, `ModuleNotFoundError: No module named 'pytorch_lightning'`. (More details below.)

According to [this issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/2653) (https://github.com/PyTorchLightning/pytorch-lightning/issues/2653) this is a serialization issue when checkpointing with Pytorch Lightning.

As a workaround, perhaps you could load the model using your pytorch lightning environment and save it again using the `save_weights_only` option in Pytorch Lightning? Or if you have an alternative solution, please let us know. 

Thanks in advance!

Walter

---

## Code to reproduce

Using the function below to model a ResNet18 model with your pretrained weights:

```python
def get_model_ciga(path='_ckpt_epoch_9.ckpt'):
    """Model downloaded from: https://github.com/ozanciga/self-supervised-histopathology
    """
    
    from torchvision import models
    def load_model_weights(model, weights):

        model_dict = model.state_dict()
        weights = {k: v for k, v in weights.items() if k in model_dict}
        if weights == {}:
            print('No weight could be loaded..')
        model_dict.update(weights)
        model.load_state_dict(model_dict)

        return model

    model = models.__dict__['resnet18'](pretrained=False)
    state = torch.load(path, map_location='cuda:0')

    state_dict = state['state_dict']
    for key in list(state_dict.keys()):
        state_dict[key.replace('model.', '').replace('resnet.', '')] = state_dict.pop(key)

    model = load_model_weights(model, state_dict)

    return model.cuda() 
```
## Error 

This gives this error:

```bash
/envs/py38/lib/python3.8/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    763     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    764     unpickler.persistent_load = persistent_load
--> 765     result = unpickler.load()
    766 
    767     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

ModuleNotFoundError: No module named 'pytorch_lightning'
```

**Comment by wdeback** [comment]
Not a solution, but as a quickfix, one can of course install [pytorch-lightning](https://github.com/PyTorchLightning/pytorch-lightning):

`pip install pytorch-lightning`

after which loading the model work.

**Comment by ozanciga** [comment]
Hey Walter,

Thanks for using our work :) 

Good point, while Lightning is being adopted more, it is not yet ubiquitous so I saved the model again with torch.save()  at this link: https://github.com/ozanciga/self-supervised-histopathology/releases/tag/model 

You can just change the path to pytorch_native_ckpt_epoch_9.ckpt , and it should run the same.

Let me know if this works for you.

**Comment by wdeback** [comment]
Thanks, Ozan! 

I can confirm the [new model checkpoint](https://github.com/ozanciga/self-supervised-histopathology/releases/tag/model) works, also without having `pytorch-lightning` installed.
