### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by alqurri77** [ozanciga/self-supervised-histopathology#12]
Hi;

I'm getting "OSError: Unable to open file (file signature not found)" when calling  "model.load_weights(MODEL_PATH )" using Tensorflow?

**Comment by ozanciga** [comment]
this is a pytorch model. if you want to use it for tensorflow you need to transfer those weights (e.g., using onnx or with something like this: https://dmolony3.github.io/Pytorch-to-Tensorflow.html)

if you do please let me know i'd be happy to add it to the available weights here

**Comment by alqurri77** [comment]
Is the model saved in ONNX format? 
Because - correct me if I'm wrong- the model need to be saved in ONNX format, before you could read in in Keras.

**Comment by andreped** [comment]
@alqurri77 I have converted the pretrained model to both ONNX and TF/Keras if you want to use the model in these frameworks.

Might be a good idea to add these to the release, @ozanciga, if people are interested?
