### ISSUE TITLE
comparison wit Imagenet 

### ISSUE THREAD

**Issue by alqurri77** [ozanciga/self-supervised-histopathology#13]
Hi;

Just to understand your result. When you compare it with Imagenet initialization.  Did you compare it with simCLR pretrained weights (https://github.com/google-research/simclr) or with Imagenet (by setting models.resnet18(pretrained=True).

Thank you!

**Comment by ozanciga** [comment]
@alqurri77 
Imagenet (by setting models.resnet18(pretrained=True)
best,

**Comment by alqurri77** [comment]
Thank you!
