### ISSUE TITLE
How can a self-supervised model pretrained on Resnet18 be transferred to Resnet34, Resnet50 and Resnet101?

### ISSUE THREAD

**Issue by Pak287** [ozanciga/self-supervised-histopathology#15]
Hi~
It is very nice work! I have a little puzzle and would like to consult you.

How can a self-supervised model pretrained on Resnet18 be transferred to Resnet34, Resnet50 and Resnet101?
Considering that the network structure of the former and the latter three is completely different, and I wonder how you transfer parameters between different models.

Looking forward to your reply! Thanks.

**Comment by ozanciga** [comment]
tangentially related work i've come across a while ago: Tensor Programs V: Tuning Large Neural Networks via Zero-Shot Hyperparameter Transfer

https://arxiv.org/abs/2203.03466
