### ISSUE TITLE
mutil resolution patches number?

### ISSUE THREAD

**Issue by AndrewTal** [ozanciga/self-supervised-histopathology#16]
The article mentions that each WSI can sample up to 1000 images. What is the data ratio of 10X, 20X, and 40X in this 1000 patches?

**Comment by AndrewTal** [comment]
looking forward to your reply.... thanks...

**Comment by ozanciga** [comment]
sorry i really don't remember (it's been 2 years). i would assume majority come from 20x, as that was the most common res available. we used 40x whenever dataset allowed it. so if you scan listed datasets, assume if 40x is available, that was used for sampling. if you try to assess the impact of resolution, see the 10, 20, 40x experiments for reference. hope it helps.
