### ISSUE TITLE
Question regarding input normalization

### ISSUE THREAD

**Issue by Reasat** [ozanciga/self-supervised-histopathology#2]
Hi
I have a question regarding input normalization before encoding the image. 
Are you subtracting by some means and dividing by std? Say, for Imagenet images 
```
mean=[0.485, 0.456, 0.406],
std=[0.229, 0.224, 0.225]
```

**Comment by ozanciga** [comment]
Hi Reasat, 

We use 

```
mean=[0.5, 0.5, 0.5]
std=[0.5, 0.5, 0.5]
```

for the self supervised experiments.

By the way, in our experiments we observed negligible difference between the values you provided and 0.5. In fact for some experiments we found 0.5 performed significantly better than ImageNet stats.
